services:
  postgres:
    image: postgres:16.0-alpine3.18
    env_file:
      - ../.env.development
    ports:
      - "5432:5432"
    networks:
      - default-network
    volumes:
      - taskflowing_data:/var/lib/taskflowing

  spring:
    image: matheushdas/taskflowing-api
    restart: always
    build: ..
    environment:
      spring.datasource.url: jdbc:postgresql://postgres:5432/taskflowing-db
      spring.datasource.username: taskflowing-user
      spring.datasource.password: taskflowing-pass
    ports:
      - "8080:8080"
    networks:
      - default-network
    command:
      - mvn spring-boot:run
    depends_on:
      - postgres

networks:
  default-network:
    driver: bridge
volumes:
  taskflowing_data:
